[package]
name = "basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mailgun-rs = "0.1.6"
tokio = { version = "1.28.1", features = ["full"] }
dotenv = "0.15.0"
